### PR TITLE
Merging latest SWC styles to library-shell

### PR DESCRIPTION
**Pull request by jt14den**
I merged https://github.com/swcarpentry/styles from gh-pages branch into library-shell. You can see how the latest style looks rendered here: http://www.tim-dennis.com/library-shell/

@weaverbel  can you take a look at the rendered version? 

I'm a bit unclear about if the preference is to clean up the commit history (and how via git rebase) from swcarpentry/styles. I've reached the edge of my git skills :)

### CODE REVIEW

**Comment by jt14den** [comment]
@drjwbaker I don't want to merge my own PR and @weaverbel is still vacating. Do you like the way the exercises are unfurled in the new style <http://www.tim-dennis.com/library-shell/01-intro-shell/>? would like to get this merged before the sprint.

**Comment by drjwbaker** [comment]
@jt14den What do you mean by 'unfurled'? I can't see any obvious difference!

**Comment by jt14den** [comment]
@drjwbaker The challenges aren't hidden, they are opened up. This was a recent change (a month ago) on the SWC lessons.

**Comment by drjwbaker** [comment]
Right. I see. I think that layout works better.

**Pull request merged**
